# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' adjusted weights
#'
#' @param matrix of the predicted  values
#'
#' @export
w <- function(zs) {
    .Call(`_PS6package_w`, zs)
}

#' predicted zvalues
#'
#' @param x matrix of value
#' @param y actual values
#' @param weight weight for each model
#' @param sd deviations
#'
#' @export
z <- function(x, y, weight, sd) {
    .Call(`_PS6package_z`, x, y, weight, sd)
}

