# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform EBMA using C++
#'
#' @param x numeric x values
#' @param y observed outcomes
#' @param weights weights of each model
#' @param sd deviation
#' @param limit change before model stops
#'
#' @export
emba_calculate <- function(x, y, weights, sd, limit) {
    .Call('_PS6package_emba_calculate', PACKAGE = 'PS6package', x, y, weights, sd, limit)
}

#' adjusted weights
#'
#' @param matrix of the predicted  values
#'
#' @export
w <- function(zs) {
    .Call('_PS6package_w', PACKAGE = 'PS6package', zs)
}

#' predicted zvalues
#'
#' @param x matrix of value
#' @param y actual values
#' @param weight weight for each model
#' @param sd deviations
#'
#' @export
z <- function(x, y, weight, sd) {
    .Call('_PS6package_z', PACKAGE = 'PS6package', x, y, weight, sd)
}

